language: rust
sudo: required

dist: trusty
rust:
  - stable
  # beta
  # nightly

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 7
  - nvm use 7
  - npm install -g mocha
  - npm install

script: |
  npm test